package:
  name: ipymd
  version: "0.1.2.dev"

build:
  number: 1

source:
  git_url: https://github.com/rossant/ipymd.git
  git_rev: master

requirements:
  build:
    - python
    - pyyaml
    - setuptools

  run:
    - pyyaml
    - python
    - notebook


about:
  home: https://github.com/rossant/ipymd
  license: BSD
  summary: 'Replace .ipynb with .md in the IPython Notebook'
