package:
  name: discretizer
  version: "0.4.1"

source:
  git_rev: v0.4.1
  git_url: https://gitlab.kwant-project.org/r-j-skolasinski/discretizer.git

requirements:
  build:
    - python
    - setuptools
    - sympy
    - numpy
  run:
    - python
    - sympy
    - kwant
    - numpy

# test:
#   imports:
#     - discretizer

about:
  home: https://gitlab.kwant-project.org/r-j-skolasinski/discretizer
  license: BSD
